# Generated by Django 5.2.7 on 2026-01-06 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to=settings.AUTH_USER_MODEL, verbose_name='bank owner'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.EmailField(default='admin@enigmatix.io', max_length=100),
        ),
    ]
